baseurl = "http://test.grundschule-anzefahr-niederwald.de/"
languageCode = "de-DE"
title = "Grundschule Anzefahr-Niederwald"
theme = "hugo-creative-theme"
googleAnalytics = ""

# Define the number of posts per page
paginate = 10

[taxonomies]
  category = "categories"
  tag = "tags"

[params]

	# You can use Markdown syntax for urls [text](//url.to/source) for
	# most longer texts.

	# All icons using Fontawesome's icon font. Look at http://fontawesome.io/icons/
	# for more icons. The icons are represented by their corresponding
	# CSS class.

	# All projects of the portfolio are defined in their own files.
	# You can find example projects at 'exampleSite/data/projects'. Copy the 'projects'
	# folder into the 'data' directory at the root of this Hugo site.
	# For more information take a look at the README.

	# To provide some metadata for search engines feel free to add some
	# information about you and your website.
	name = "TODO Your name"
	description = "TODO Your description"

	# The path must be relative to the static folder
	favicon = "favicon.ico"

    # Format dates with Go's time formatting
    date_format = "January 2, 2006"

	# Navigation
	[params.navigation]
		brand = "Grundschule Anzefahr-Niederwald"
 
        [[params.navigation.pre.links]]
            name = "Aktuelles"
            url  = "/news"

		[params.navigation.links]
			about     = "Unsere Schule"
			services  = "Ziele"
			portfolio = "Projekte"
            team      = "Team"
			contact   = "Kontakt"


	# Hero section
	[params.hero]
		# To change the background of the hero section, replace the 'header.jpg' at './static/img' with your own.
		slogan     = "Voneinander lernen, miteinander arbeiten, füreinander leben"
		subtitle   = "Peter Petersen"
		buttonText = "Wollen Sie mehr erfahren?"

    # Enable and disable widgets for the right sidebar
    [params.widgets]
        categories = true
        tags = true
        search = true

	# About section
	[params.about]
		headline    = "Unsere Schule"
        #buttonText  = "Get started!"
		description = """
### Größe

Die Grundschule Anzefahr-Niederwald ist eine einzügige Grundschule südlich von Kirchhain, 
im schönen Ohmtal gelegen. Im aktuellen Schuljahr 2016/2017 besuchen 73 Schüler und 
Schülerinnen aus den Dörfern Anzefahr, Niederwald und Sindersfeld, sowie auch Kinder aus 
Stausebach unsere Schule. 
Der Unterricht findet in 4 Lerngruppen an zwei Standorten statt: 

Am Standort Anzefahr werden im laufenden Schuljahr 14 Kinder in Klasse 3 und 20 Kinder in 
Klasse 4 unterrichtet.

Am Standort Niederwald werden aktuell 18 Kinder in Klasse 2 und 21 Kinder in Klasse 1 
unterrichtet. Dort befindet sich auch die Schulbetreuung, in der in diesem Schuljahr 25 
Kinder von 3 Betreuerinnen betreut werden.

Der Sportunterricht findet im Bürgerhaus Anzefahr statt.

Der Schule wird bei den nicht-pädagogische Aufgaben von einer Sekretärin, zwei 
Hausmeistern und zwei Reinigungskräften unterstützt.

### Die Standorte und ihre Entwicklung

#### Anzefahr

Das Schulgebäude in Anzefahr liegt zwar mitten im Dorf, jedoch grenzt es an die 
umliegenden Felder, so dass man schnell im Grünen ist. Im Schulgebäude befinden sich 
zwei Klassenräume und das Lehrerzimmer; es wird durch einen Anbaukomplex ergänzt. 
Hinter dem Schulgebäude ist eine große Wiese, auf der die Kinder sich frei bewegen und 
spielen können: Fußball, Klettern, Balancieren, im Sand spielen oder sich im Schatten des 
Bauwagens unterhalten oder lesen. Ein kleiner Schulgarten ermöglicht im Sachunterricht das 
Pflanzen und Beobachten von Blumen.

#### Niederwald

Das Schulgebäude in Niederwald befindet sich ebenfalls im Dorfkern. Neben zwei 
Klassenräumen beherbergt es die Betreuungsräume, die Verwaltung, eine Bibliothek und 
den Lehrmittelraum der Schule. Das Schulgelände bietet viel Platz zum Toben und freien 
Spielen. In einem großen Sandkasten werden ganze Städte gebaut, der angrenzende kleine 
Obstgarten lädt die Kinder immer wieder zu einem Besuch ein.

Da die Gebäude nicht weiter ausgebaut werden können, sind die Klassenzimmer gleichzeitig 
Mehrzweckräume für Feiern und Gespräche, PC-Räume, Kunstsaal, Musikraum und 
Förderraum.

Die Betreuung befindet sich im zweiten Obergeschoss in einem Teil der ehemaligen
Lehrerwohnung. Sie wurde 2012 (?) eingerichtet und in Elternleistung renoviert, um dem 
Bedarf an Betreuungsplätzen entgegen zu kommen. Leider sind die räumlichen 
Möglichkeiten auch hier begrenzt, so dass nur ca. 1/3 der Kinder ein Platz angeboten 
werden kann. Die Betreuung wird vom Förderverein der Schule, in Kooperation mit dem 
Landkreis Marburg-Biedenkopf organisiert. Sie ist montags bis freitags nach dem Unterricht 
von 11:20 bis 14:30 Uhr geöffnet; auf Wunsch können die Kinder auch bis 15:00 Uhr 
angemeldet werden.

Eine Besonderheit unserer Schule liegt darin, dass sie sich aus den vier ehemals 
selbständigen Volksschulen Anzefahr, Betziesdorf, Niederwald und Sindersfeld zu einer 
Grundschule mit zunächst drei Standorten, seit 2013 mit zwei Standorten entwickelt hat. Die 
Entwicklung zu einer gemeinsamen Beschulung der Kinder der vorwiegend katholisch 
ausgerichteten Dörfer Anzefahr und Sindersfeld sowie der vorwiegend evangelisch 
ausgerichteten Dörfer Betziesdorf und Niederwald hat auch die Beziehungen der Menschen 
in dieser Region intensiviert.

### Wie sich alles entwickelte:

**1972:** Die Schüler der Klassen 3 und 4 aus Anzefahr und Niederwald werden zu 
Jahrgangsklassen zusammengefasst. Die Klasse 4 wird in Anzefahr unterrichtet, die Klasse 
3 in Niederwald. Die Klassen 1 und 2 bilden eine Kombinationsklasse. Anzefahr und 
Niederwald bilden einen Schulverbund, sind aber noch selbständige Schulen.

**1973:** Die selbständige Schule Sindersfeld wird geschlossen und ihre Schüler gehören von 
da an zum Schulverbund Anzefahr-Niederwald.

**1977:** Die bis dahin selbständigen Schulen Anzefahr und Niederwald werden aufgehoben. 
Es wird die Grundschule Anzefahr-Niederwald gegründet, und zwar mit den Standorten 
Anzefahr und Niederwald.

**1983:** Die selbständige Schule Betziesdorf wird aufgehoben und in die Grundschule 
Anzefahr-Niederwald als Außenstelle integriert. Somit bekommt die Grundschule Anzefahr-
Niederwald noch einen Standort, nämlich Betziesdorf.
In Betziesdorf werden nur Betziesdorfer Kinder unterrichtet, während die Jahrgangsklassen 
der Standorte Anzefahr und Niederwald aus den Kindern der Dörfer Anzefahr, Niederwald 
und Sindersfeld zusammengesetzt werden. An welchem Standort sie unterrichtet werden, 
richtet sich danach, an welchem Standort das jeweilige erste Schuljahr eingeschult wird. 

**2013:** Die Außenstelle Betziesdorf wird geschlossen. Die Betziesdorfer Kinder besuchen seit 
diesem Schuljahr die Grundschule Bürgeln.
"""

    # Footer section
    [params.footer]
        name = "Impressum"
        url = "/impressum/"


	# Service section
	[params.services]
		headline = "Wir stärken unsere Kinder für die Zukunft"

        [[params.services.list]]
            icon = "fa-paper-plane"
            title = "Selbständigkeit"
            description = "Unsere Schüler werden zu demokratischem Denken und Handeln angeregt. Sie lernen selbständiges Lernen und sie werden sozialkompetent, selbstbewusst und stark gemacht."

        [[params.services.list]]
            icon = "fa-diamond"
            title = "Förderung"
            description = "Unsere Schüler werden individuell gefördert und gefordert. Sie lernen außerschulische Lernorte kennen und führen standortübergreifende Projekte durch."

    		[[params.services.list]]
            icon = "fa-search"
            title = "Transparenz"
            description = "Wir öffnen unsere Schule im Inneren und nach außen hin. Unsere Lehrer gehen professionell und offen miteinander um."

        [[params.services.list]]
            icon = "fa-heart"
            title = "Geborgenheit"
            description = "Unsere Schüler sollen sich in der Schule und der Gemeinschaft wohl fühlen. Wir achten auf gesunde Ernährung und Bewegung."


    # Portfolio modals
	[params.portfolio.modal]
        client = "Client"
        date = "Datum"
        category = "Kategorie"
        buttonText = "Schließen"

    # Aside section
	[params.aside]
		headline = "Interessieren Sie sich für den Förderverein?"

		[[params.aside.button]]
			text = "Flyer"
			link = "/download/Flyer.pdf"

            [[params.aside.button]]
			text = "Beitrittserklaerung"
			link = "/download/Beitrittserklaerung.pdf"

	# Contact section
	[params.contact]
		headline = "Kontaktieren Sie uns!"
		description = "Sie haben Fragen oder interessieren sich für unsere Schule? Das ist toll! Rufen Sie uns an oder schreiben Sie uns eine E-Mail und wir melden uns sobald wie möglich!"
		phone = "+49 6422 1715"
		fax = "+49 6422 898282"
		email = "poststelle@grundschule.anzefahr-niederwald.schulverwaltung.hessen.de"

		[params.contact.address]
			name = "Grundschule Anzefahr-Niederwald"
			street = "Obergasse 20"
			site = "35274 Kirchhain"

	# Google Maps section
	[params.location]
	 	latitude  = "50.82812"
	 	longitude = "8.88123"
		maps_api_key = "AIzaSyADWFNGGFj-L8qCGIJg794q9r8Fe9_4rX0"
		
		# kinda dirty way to add second marker for anzefahr
		latitude2  = "50.846523"
	 	longitude2 = "8.865679" 
	 	
  # Team section
  [params.team]
    enable = true
    # Possibility to center items
    center = true
    title = "Unser Team"
    subtitle = "Die höchste Form der Kommunikation ist der Dialog. <br/><cite>-- August Everding</cite>"
    description = "An der Grundschule Anzefahr-Niederwald arbeiten derzeit 6 KollegInnen."

    # All team member's pictures are stored under 'static/img/team'.
    # Replace them with your own too.
    # Suggestion: Image size should be at least 360px*360px or the alignment might be affected.
    [[params.team.members]]
      img = "Katja_Wessel.jpg"
      name = "Katja Wessel"
      position = "Schulleiterin"
      #reportsTo = "CTO"
      livesIn = "[Marburg, Deutschland](#some-maps-url)"
      scope = [
        "Klassenlehrerin der [Eulenklasse](#)"
      #  "Maintainer for [awesome-project](#)",
      #  "Open Source [community management](#)"
      ]
      # For bio markdown and even multiline strings are available.
      bio = """Katja Wessel ist Schulleiterin seit 200x und Klassenlehrerin der Eulenklasse."""
      social = [
        ["fa-twitter", "#"],
        ["fa-facebook", "#"],
        ["fa-linkedin", "#"]
      ]

	[[params.team.members]]
      img = "Nuhn.jpg"
      name = "Frau Nuhn"
      position = "Klassenlehrerin"
      scope = [
      	"Klassenlehrerin der [Pinguinklasse](#)"
      ]
      bio = """Frau Nuhn ist Fachlehrerin für Sport und Schwimmen."""

	[[params.team.members]]
      img = "Velten.jpg"
      name = "Frau Velten"
      position = "Klassenlehrerin"
      scope = [
      	"Klassenlehrerin der [Tigerklasse](#)"
      ]
	
	[[params.team.members]]
      img = "Barho.jpg"
      name = "Frau Barho"
      position = "Klassenlehrerin"
      scope = [
      	"Klassenlehrerin der [Affenklasse](#)"
      ]

	[[params.team.members]]
      img = "Siekmann.jpg"
      name = "Frau Siekmann"
      position = "BFZ-Lehrerin"
      
	[[params.team.members]]
      img = "Imkamp.jpg"
      name = "Herr Imkamp"
      position = "BFZ-Lehrer"
